# Generated by Django 2.0.6 on 2018-06-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntakibariapp', '0003_auto_20180627_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total_household',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.DateField(db_index=True),
        ),
    ]
