# Generated by Django 2.0.6 on 2018-06-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntakibariapp', '0004_auto_20180627_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], db_index=True, default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='member',
            name='total_household',
            field=models.PositiveIntegerField(db_column='Total Person in your house', db_index=True, default=0),
        ),
    ]
