# Generated by Django 2.0.6 on 2018-06-30 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ntakibariapp', '0005_auto_20180628_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=80)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('image_of_area', models.ImageField(blank=True, upload_to='photos')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(db_index=True, default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
