# Generated by Django 2.0.6 on 2018-06-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntakibariapp', '0007_auto_20180630_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
