# Generated by Django 2.0.6 on 2018-06-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntakibariapp', '0008_auto_20180630_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(db_index=True, default=None, max_length=9, null=True),
        ),
    ]
