# Generated by Django 2.0.6 on 2018-07-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntakibariapp', '0010_added_community_work__tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_work',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
