# Generated by Django 2.0.6 on 2018-07-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntakibariapp', '0011_added_community_work_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community_work',
            old_name='description',
            new_name='work_description',
        ),
    ]
