# Generated by Django 2.0.6 on 2018-07-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntakibariapp', '0012_auto_20180701_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=60)),
                ('event_description', models.TextField()),
                ('event_photo', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
