# Generated by Django 2.0.6 on 2018-07-02 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ntakibariapp', '0013_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
