# Generated by Django 2.0.6 on 2018-07-03 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ntakibariapp', '0014_gallery_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun_title', models.CharField(db_index=True, max_length=40)),
                ('fun_description', models.TextField()),
                ('fun_photo', models.ImageField(blank=True, upload_to='photos')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
