# Generated by Django 2.0.6 on 2018-07-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntakibariapp', '0016_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fun',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AddField(
            model_name='post',
            name='project_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('fun', 'Funs'), ('project', 'project'), (None, 'category')], max_length=20),
        ),
    ]
